build:
  tests:
    override:
      -
        command: 'bin/phpunit --coverage-clover=coverage.clover'
        coverage:
          file: 'coverage.clover'
          format: 'clover'

checks:
  php:
    code_rating: true
    duplication: true
